export const projectTour = {
  id: 'projects',
  steps: [
    {
      target: null,
      title: 'Benvenuto nel tuo primo progetto! 🏗️',
      content: 'Ti mostreremo le funzionalità essenziali per gestire il cantiere in modo efficace.',
      placement: 'center',
    },
    {
      target: 'h1',
      title: 'Nome del Progetto',
      content: 'Questo è il tuo cantiere. Qui troverai tutte le informazioni e gli strumenti per gestirlo.',
      placement: 'bottom',
      padding: 12,
    },
    {
      target: '[role="tablist"]',
      title: 'Sezioni del Progetto',
      content: 'Organizza il lavoro in sezioni: Cantiere (panoramica), Lavori (task e milestone) e Info & Team (partecipanti e documenti).',
      placement: 'bottom',
      padding: 8,
    },
    {
      target: null,
      title: 'Esplora le Sezioni 📋',
      content: 'Clicca su "Cantiere" per una panoramica, su "Lavori" per gestire task e milestone, e su "Info & Team" per i dettagli del team.',
      placement: 'center',
      clickTab: 'overview',
    },
    {
      target: '[role="tabpanel"]',
      title: 'Panoramica Cantiere 🏗️',
      content: 'Qui vedi lo stato del progetto, le statistiche principali e un feed delle attività recenti.',
      placement: 'bottom',
      padding: 8,
      clickTab: 'tasks',
    },
    {
      target: '[role="tabpanel"]',
      title: 'Gestione Lavori ✅',
      content: 'Nella sezione Lavori puoi creare task, organizzarli in milestone, e monitorare il progresso. Ogni task ha un responsabile e una scadenza.',
      placement: 'bottom',
      padding: 8,
      clickTab: 'team',
    },
    {
      target: '[role="tabpanel"]',
      title: 'Team e Documenti 👥',
      content: 'Qui gestisci i partecipanti al progetto, carichi documenti, gestisci le variazioni e comunichi con il team.',
      placement: 'bottom',
      padding: 8,
    },
    {
      target: null,
      title: 'Pronto a Iniziare! 🚀',
      content: 'Invita i membri del team, crea i tuoi task e inizia a organizzare il cantiere. Buon lavoro!',
      placement: 'center',
    },
  ],
};